### ISSUE TITLE
'nan' problem in d1 and BlackScholes.price

### ISSUE THREAD

**Issue by masanorihirano** [pfnet-research/pfhedge#484]
This hardly happens but I faced this issue:

```
import torch
from pfhedge.instruments import EuropeanOption
from pfhedge.instruments import BrownianStock
derivative = EuropeanOption(BrownianStock(), maturity=5/250)
from pfhedge.nn import BlackScholes

BlackScholes(derivative).price(log_moneyness=torch.tensor(1), time_to_maturity=torch.tensor(0), volatility=torch.tensor(0.2))
# works normally: tensor(1.7183)
BlackScholes(derivative).price(log_moneyness=torch.tensor(0), time_to_maturity=torch.tensor(0), volatility=torch.tensor(0.2))
# error

BlackScholes(derivative).price(log_moneyness=torch.tensor(1e-7), time_to_maturity=torch.tensor(0), volatility=torch.tensor(0.2))
# tensor(1.1921e-07)
BlackScholes(derivative).price(log_moneyness=torch.tensor(-1e-7), time_to_maturity=torch.tensor(0), volatility=torch.tensor(0.2))
# tensor(0.)
```
Considering the continuity of pricing, the error case should return tensor of 0.

This issue comes from the problem in black-sholes d1 calculation:

https://github.com/pfnet-research/pfhedge/blob/c342b52ba2d8c6182304a20a0db21e83130799ef/pfhedge/nn/modules/bs/european.py#L222
https://github.com/pfnet-research/pfhedge/blob/c342b52ba2d8c6182304a20a0db21e83130799ef/pfhedge/nn/functional.py#L521
-> `(0.0).div(0.0)` returns `nan`
Then, 
https://github.com/pfnet-research/pfhedge/blob/c342b52ba2d8c6182304a20a0db21e83130799ef/pfhedge/nn/functional.py#L473
https://github.com/pytorch/pytorch/blob/71f889c7d265b9636b93ede9d651c0a9c4bee191/torch/distributions/normal.py#L79-L82
in `self._validate_sample(value)`,
https://github.com/pytorch/pytorch/blob/71f889c7d265b9636b93ede9d651c0a9c4bee191/torch/distributions/distribution.py#L286-L294
these validations returns `ValueError` because of nan.

I think,
```
BlackScholes(derivative).price(log_moneyness=torch.tensor(0), time_to_maturity=torch.tensor(0), volatility=torch.tensor(0.2))
```
should return tensor of 0, but, I'm not sure if we should fix the calculation in d1 or make an exceptional routine for this edge case.

**Comment by masanorihirano** [comment]
FYI:

Currently, I'm using the following workaround:
```
pricer: Callable[[BaseDerivative], torch.Tensor] = lambda derivative: BlackScholes(derivative).price(
                        log_moneyness=derivative.log_moneyness().masked_fill_(derivative.log_moneyness() == 0.0, -1e-7),
                        time_to_maturity=derivative.time_to_maturity(), volatility=derivative.ul().volatility)
```

**Comment by masanorihirano** [comment]
In the case of Lookback option, the workaround is more complicated:

```
pricer: Callable[[BaseDerivative], torch.Tensor] = lambda derivative: BlackScholes(derivative).price(
    log_moneyness=derivative.log_moneyness().masked_fill_(derivative.log_moneyness() == 0.0, -1e-7),
    time_to_maturity=derivative.time_to_maturity(), volatility=derivative.ul().volatility,
    max_log_moneyness=derivative.max_log_moneyness().masked_fill_(
        derivative.max_log_moneyness() == derivative.log_moneyness(), -1e-7))
```

**Comment by masanorihirano** [comment]
I found this issue is also common to each greeks calculation. Thus, I think we have to define 0/0 in d1 and d2 to solve all problems at onece. Careful considering is necessary because, mathematically, it cannot be defined.

**Comment by simaki** [comment]
Thank you so much for sharing that! Really good catch.

clamping the denominator should solve it.

```py
import torch


print(torch.finfo().tiny)


def d1(s, w):
    # w = v * t.sqrt()
    return (s + w ** 2 / 2).div(w)

def d1_new(s, w):
    # w = v * t.sqrt()
    return (s + w ** 2 / 2).div(w.clamp(min=torch.finfo().tiny))


output = d1(torch.tensor(-1e-7), torch.zeros(1))
print(output)
# tensor([-inf])
output = d1(torch.tensor(0.0), torch.zeros(1))
print(output)
# tensor([nan])
output = d1(torch.tensor(1e-7), torch.zeros(1))
print(output)
# tensor([inf])

output = d1_new(torch.tensor(-1e-7), torch.zeros(1))
print(output)
# tensor([-8.5071e+30])
output = d1_new(torch.tensor(0.0), torch.zeros(1))
print(output)
# tensor([0.])
output = d1_new(torch.tensor(1e-7), torch.zeros(1))
print(output)
# tensor([8.5071e+30])
```

This fix gives the desired price:

```
from pfhedge.nn.functional import ncdf

log_moneyness = torch.tensor(1e-7)
d1 = d1_new(log_moneyness, torch.zeros(1))
d2 = d1
price = log_moneyness.exp() * ncdf(d1) - ncdf(d2)
print(price)
# tensor([1.1921e-07])

log_moneyness = torch.tensor(0.0)
d1 = d1_new(log_moneyness, torch.zeros(1))
d2 = d1
price = log_moneyness.exp() * ncdf(d1) - ncdf(d2)
print(price)
# tensor([0.])

log_moneyness = torch.tensor(-1e-7)
d1 = d1_new(log_moneyness, torch.zeros(1))
d2 = d1
price = log_moneyness.exp() * ncdf(d1) - ncdf(d2)
print(price)
# tensor([0.])
```

I think this is a simple and quick fix. What do you think?

**Comment by masanorihirano** [comment]
According to your fix,
```
BlackScholes(derivative).delta(log_moneyness=torch.tensor(0), time_to_maturity=torch.tensor(0), volatility=torch.tensor(0.2))
Out[3]: tensor(0.5000)
```
It sounds good.

**Comment by masanorihirano** [comment]
As I mentioned previously, I think it is unnecessary that all greeks are correctly calculated at the maturity.

However, I also found the same issue (0/0 issue) in:
https://github.com/pfnet-research/pfhedge/blob/c342b52ba2d8c6182304a20a0db21e83130799ef/pfhedge/nn/modules/bs/european.py#L142
https://github.com/pfnet-research/pfhedge/blob/c342b52ba2d8c6182304a20a0db21e83130799ef/pfhedge/nn/modules/bs/european.py#L197

**Comment by simaki** [comment]
Thank you, they should be fixed as well!

**Comment by simaki** [comment]
May I patch this? I can in around a week, but it would be more than welcome if you could kindly send a patch.

**Comment by masanorihirano** [comment]
Both are OK, but I think if I make this patch, I'll do it next Tuesday or later.
Moreover, I'm not sure what is the best modification for gamma and theta because they require considerations of their limit. (i.e. limit_{x\to 0} limit_{y\to +0} x/y is not the same as limit_{y\to 0} limit_{x\to 0} x/y and limit_{x\to 0} limit_{y\to -0} x/y. Thus, we have to consider the original definition of them)

**Comment by masanorihirano** [comment]
At maturity, I think that the theta is 0, but the gamma is +inf when the underlier price and the strike is the same. Is it right?

**Comment by masanorihirano** [comment]
d1 and d2 could have the same issue. I'm still not sure if d1=d2=0 or not when the underlier price and the strike is the same...

**Comment by simaki** [comment]
> Both are OK, but I think if I make this patch, I'll do it next Tuesday or later.

perfect!

> At maturity, I think that the theta is 0, but the gamma is +inf when the underlier price and the strike is the same. Is it right?

I think theta is -inf by Black Scholes equation.

**Comment by masanorihirano** [comment]
> I think theta is -inf by Black Scholes equation.
I have confirmed you're right.

I finally understand that npdf is [0, 1] and theta and gamma is dominated by their friction denominator
